# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Course.delete_all

Course.create!([{code: "CSC510",
                syllabus_id: "1",
                prerequisites: "Discrete Maths; Data Structures",
                course_name: "Software Engineering",
                core: true,
                channel_id: "1"},
                {code: "CSC515",
                 syllabus_id: "2",
                 prerequisites: "Software Engineering",
                 course_name: "Software Security",
                 core: false,
                 channel_id: "2"},
                {code: "CSC519",
                 syllabus_id: "3",
                 prerequisites: "Software Engineering",
                 course_name: "DevOps",
                 core: false,
                 channel_id: "3"},
                {code: "CSC710",
                 syllabus_id: "4",
                 prerequisites: "Software Engineering",
                 course_name: "Software Engineering as a human activity",
                 core: false,
                 channel_id: "4"},
                {code: "CSC712",
                 syllabus_id: "5",
                 prerequisites: "Software Engineering",
                 course_name: "Software Testing and Reliability",
                 core: false,
                 channel_id: "5"},
                {code: "CSC503",
                 syllabus_id: "6",
                 prerequisites: "Automata, Grammar and Computability",
                 course_name: "Computational Applied Logic",
                 core: true,
                 channel_id: "6"},
                {code: "CSC512",
                 syllabus_id: "7",
                 prerequisites: "Automata, Grammar and Computability; Data Structures",
                 course_name: "Compiler Construction",
                 core: true,
                 channel_id: "7"},
                {code: "CSC517",
                 syllabus_id: "8",
                 prerequisites: "UG Software Engineering",
                 course_name: "Object Oriented Design and Development",
                 core: false,
                 channel_id: "8"},
                {code: "CSC520",
                 syllabus_id: "9",
                 prerequisites: "Discrete Maths; Data Structures",
                 course_name: "Artificial Intelligence",
                 core: true,
                 channel_id: "9"},
                {code: "CSC522",
                 syllabus_id: "10",
                 prerequisites: "Discrete Maths; Data Structures",
                 course_name: "Automated Learning and Data Analysis",
                 core: false,
                 channel_id: "10"},
                {code: "CSC540",
                 syllabus_id: "11",
                 prerequisites: "Data Structures",
                 course_name: "Database Management concepts and Systems",
                 core: true,
                 channel_id: "11"},
                {code: "CSC547",
                 syllabus_id: "12",
                 prerequisites: "Operating System Principles; Computer Networks",
                 course_name: "Cloud Computing Technology",
                 core: false,
                 channel_id: "12"},
                {code: "CSC554",
                 syllabus_id: "13",
                 prerequisites: "Data Structures",
                 course_name: "Human-Computer Interaction",
                 core: false,
                 channel_id: "13"},
                {code: "CSC750",
                 syllabus_id: "14",
                 prerequisites: "Database Management concepts and Systems",
                 course_name: "Service Oriented Computing",
                 core: false,
                 channel_id: "14"},
                {code: "CSC505",
                 syllabus_id: "15",
                 prerequisites: "Discrete Maths; Data Structures",
                 course_name: "Design and Analysis of Algorithms",
                 core: true,
                 channel_id: "15"},
                {code: "CSC591F",
                 syllabus_id: "16",
                 course_name: "Foundations of Data Science",
                 core: false,
                 channel_id: "16"},
                {code: "CSC591S",
                 syllabus_id: "17",
                 course_name: "Spatial and Temporal Data Mining",
                 core: false,
                 channel_id: "17"},
                {code: "CSC541",
                 syllabus_id: "18",
                 prerequisites: "Data Structures",
                 course_name: "Advanced Data Structures",
                 core: false,
                 channel_id: "18"},
                {code: "CSC548",
                 syllabus_id: "19",
                 prerequisites: "UG Operating Systems Principles; Operating Systems Principles",
                 course_name: "Parallel Systems",
                 core: false,
                 channel_id: "19"},
                {code: "CSC591D",
                 syllabus_id: "20",
                 course_name: "Data Intensive Computing",
                 core: false,
                 channel_id: "20"},
                {code: "CSC742",
                 syllabus_id: "21",
                 prerequisites: "Advanced Data Structures",
                 course_name: "Database Management Systems",
                 core: false,
                 channel_id: "21"},
                {code: "CSC724",
                 syllabus_id: "22",
                 prerequisites: "Operating Systems Principles",
                 course_name: "Advanced Distributed Systems",
                 core: false,
                 channel_id: "22"},
                {code: "CSC530",
                 syllabus_id: "22",
                 prerequisites: "Data Structures; Design and Analysis of Algorithms",
                 course_name: "Computational Methods for Molecular Biology",
                 core: false,
                 channel_id: "22"},
                {code: "CSC555",
                 syllabus_id: "23",
                 course_name: "Social Computing",
                 core: false,
                 channel_id: "23"},
                {code: "CSC561",
                 syllabus_id: "24",
                 course_name: "Principles of Computer Graphics",
                 core: true,
                 channel_id: "24"},
                {code: "CSC591E",
                 syllabus_id: "25",
                 course_name: "Educational Data Mining",
                 core: false,
                 channel_id: "25"},
                {code: "CSC565",
                 syllabus_id: "26",
                 prerequisites: "Discrete Maths",
                 course_name: "Graph Theory",
                 core: true,
                 channel_id: "26"},
                {code: "CSC580",
                 syllabus_id: "27",
                 course_name: "Numerical Analysis",
                 core: true,
                 channel_id: "27"},
                {code: "CSC501",
                 syllabus_id: "28",
                 prerequisites: "UG Operating Systems Principles",
                 course_name: "Operating Systems Principles",
                 core: true,
                 channel_id: "28"},
                {code: "CSC506",
                 syllabus_id: "29",
                 course_name: "Architecture of Parallel Computers",
                 core: true,
                 channel_id: "29"},
                {code: "CSC570",
                 syllabus_id: "30",
                 course_name: "Computer Networks",
                 core: true,
                 channel_id: "30"},
                {code: "CSC591U",
                 syllabus_id: "31",
                 course_name: "User Experience",
                 core: false,
                 channel_id: "31"},
                {code: "CSC720",
                 syllabus_id: "32",
                 prerequisites: "Artificial Intelligence",
                 course_name: "Artificial Intelligence 2",
                 core: true,
                 channel_id: "32"},
                {code: "CSC722",
                 syllabus_id: "33",
                 prerequisites: "Artificial Intelligence",
                 course_name: "Advanced Topics in Machine Learning",
                 core: false,
                 channel_id: "33"},
               ])