# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Course.delete_all

Course.create!([{code: "CSC510",
                syllabus_id: "1",
                prerequisites: "Discrete Maths; Data Structures",
                course_name: "Software Engineering",
                core: true,
                channel_id: "1"},
                {code: "CSC515",
                 syllabus_id: "2",
                 prerequisites: "Software Engineering",
                 course_name: "Software Security",
                 core: false,
                 channel_id: "2"},
                {code: "CSC519",
                 syllabus_id: "3",
                 prerequisites: "Software Engineering",
                 course_name: "DevOps",
                 core: false,
                 channel_id: "3"},
                {code: "CSC710",
                 syllabus_id: "4",
                 prerequisites: "Software Engineering",
                 course_name: "Software Engineering as a human activity",
                 core: false,
                 channel_id: "4"},
                {code: "CSC712",
                 syllabus_id: "5",
                 prerequisites: "Software Engineering",
                 course_name: "Software Testing and Reliability",
                 core: false,
                 channel_id: "5"},
                {code: "CSC503",
                 syllabus_id: "6",
                 prerequisites: "Automata, Grammar and Computability",
                 course_name: "Computational Applied Logic",
                 core: true,
                 channel_id: "6"},
                {code: "CSC512",
                 syllabus_id: "7",
                 prerequisites: "Automata, Grammar and Computability; Data Structures",
                 course_name: "Compiler Construction",
                 core: true,
                 channel_id: "7"},
                {code: "CSC517",
                 syllabus_id: "8",
                 prerequisites: "UG Software Engineering",
                 course_name: "Object Oriented Design and Development",
                 core: false,
                 channel_id: "8"},
                {code: "CSC520",
                 syllabus_id: "9",
                 prerequisites: "Discrete Maths; Data Structures",
                 course_name: "Artificial Intelligence",
                 core: true,
                 channel_id: "9"},
                {code: "CSC522",
                 syllabus_id: "10",
                 prerequisites: "Discrete Maths; Data Structures",
                 course_name: "Automated Learning and Data Analysis",
                 core: false,
                 channel_id: "10"},
                {code: "CSC540",
                 syllabus_id: "11",
                 prerequisites: "Data Structures",
                 course_name: "Database Management concepts and Systems",
                 core: true,
                 channel_id: "11"},
                {code: "CSC547",
                 syllabus_id: "12",
                 prerequisites: "Operating System Principles; Computer Networks",
                 course_name: "Cloud Computing Technology",
                 core: false,
                 channel_id: "12"},
                {code: "CSC554",
                 syllabus_id: "13",
                 prerequisites: "Data Structures",
                 course_name: "Human-Computer Interaction",
                 core: false,
                 channel_id: "13"},
                {code: "CSC750",
                 syllabus_id: "14",
                 prerequisites: "Database Management concepts and Systems",
                 course_name: "Service Oriented Computing",
                 core: false,
                 channel_id: "14"}

               ])